<DashboardScreen>

    BoxLayout:

        orientation: "vertical"

        Label:

            text: "Dashboard"

            font_size: "30sp"

        Button:

            text: "Register User"

            size_hint_y: None

            height: 50

            on_release:

                app.root.current = "register"

        Button:

            text: "Logout"

            size_hint_y: None

            height: 50

            on_release:

                app.root.current = "login"
